[package]
name = "ui"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
tui = "0.19.0"

input = { path = "../input" }
twitch = { path = "../twitch" }
